### ISSUE TITLE
crypto library does not load on osx and windows jdk11

### ISSUE THREAD

**Issue by llxia** [ibmruntimes/openj9-openjdk-jdk11#98] opened 2019-01-22 19:02 UTC
New test [cmdLineTester_CryptoTest](https://github.com/eclipse/openj9/pull/4376) is created to test OpenSSL natives are being loaded properly. The test passed on other platforms, but it failed on osx and windows jdk11 with message `Warning: Native crypto library load failed. Using Java crypto implementation`

osx jdk8 also failed. windows jdk8 worked as expected.
 
Please see comment for detail: https://github.com/eclipse/openj9/pull/4376#issuecomment-456509998

**Comment by pshipton** [comment] 2019-01-23 03:33
Copying and modifying my comments from eclipse/openj9#4376 here.

For osx (jdk11) I see both libjncrypto.dylib and libcrypto.1.1.dylib present. Not sure why the crypto library is failing to load. osx jdk8 doesn't work either.

For Windows, I can confirm that OpenJ9 builds with `--enable-openssl-bundling`, however the crypto dll doesn't appear to be included in the build. I see it in the jdk8 build but not jdk11.
```
00:45:47 + bash configure --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --with-boot-jdk=/cygdrive/c/openjdk/jdk11 --with-toolchain-version=2017 --disable-ccache --with-openssl=/cygdrive/c/OpenSSL-1.1.1-x86_64 --enable-openssl-bundling```

**Comment by pshipton** [comment] 2019-01-23 03:34
@enasser

**Comment by enasser** [comment] 2019-01-23 15:35
@pshipton The issue with macos is that libjncrypto.dylib is linked to /usr/local/lib/libcrypto.1.1.dylib instead of linking with rpath i.e @rpath/libcrypto.1.1.dylib. In my local system,  /usr/local/lib/libcrypto.1.1.dylib exists and it works. The issue can be work around by creating a symlink from /usr/local/lib/libcrypto.1.1.dylib to the actual library.

**Comment by pshipton** [comment] 2019-01-23 15:46
@nasser this is not an acceptable solution, we want the openssl acceleration to work out of the box without the user having to make changes like this.

**Comment by enasser** [comment] 2019-01-23 16:02
@pshipton Am not suggesting it's solution for the release. It is just a work around for the performance tests if any till we fix it .

**Comment by enasser** [comment] 2019-01-24 06:50
The issue is that libcrypto.1.1.dylib by default is built with  /usr/local/lib as the path instead of rpath. We can change the path while building crypto. However, if we use pre-built crypto, we will still have issue. Am trying to understand whether is any way to make it rpath while linking  the pre-built library. 

```
libcrypto.1.1.dylib:
	/usr/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

**Comment by pshipton** [comment] 2019-01-25 18:21
This is fixed on jdk11 by #102 and in the 0.12 release branch by #105.
The tests are enabled by https://github.com/eclipse/openj9/pull/4437 and in the 0.12 release branch by https://github.com/eclipse/openj9/pull/4452

The osx fix for jdk8 is WIP in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/244. ATM it doesn't work.

**Comment by pshipton** [comment] 2019-01-28 00:13
ibmruntimes/openj9-openjdk-jdk8#244 is merged. The fix for the 0.12 release is pending.

jdk8 tests are https://github.com/eclipse/openj9/pull/4450 and for the 0.12 release branch https://github.com/eclipse/openj9/pull/4471

**Comment by pshipton** [comment] 2019-01-28 04:39
fix for the 0.12 release branch https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/245

**Closed by pshipton** 2019-01-28 04:39 UTC
